const MAIN_BG_COLOR = "black";
const MAIN_LINES_COLOR = "white";

export default {
  ENTITY_BG_COLOR: MAIN_BG_COLOR,
  ENTITY_TEXT_COLOR: MAIN_LINES_COLOR,
  ENTITY_BG_COLOR_DEBUG: "#000",
  ENTITY_TEXT_COLOR_DEBUG: "#fff",
  ENTITY_TYPEEFFECTSPEED: 100,
  ENTITY_TYPEEFFECTSPEED_DEBUG: 100,
  ENTITY_HASTYPEEFFECT_DEBUG: true,
  ENTITY_STROKE_COLOR: MAIN_LINES_COLOR,
  ENTITY_STROKE_WIDTH: 1,
  ORGANISM_STROKE_COLOR: MAIN_LINES_COLOR,
  DRAGLINE_STROKE_COLOR: MAIN_LINES_COLOR,
  CANVAS_BG_COLOR: MAIN_BG_COLOR,
  WAIT_AFTER_ANSWER_SELECT: 700,
  WAIT_UNTIL_GAME_RESTART: 10000,
};
