export default {
  ENTITY_BG_COLOR: "#000",
  ENTITY_TEXT_COLOR: "#fff",
  ENTITY_BG_COLOR_DEBUG: "#fff",
  ENTITY_TEXT_COLOR_DEBUG: "#000",
  WAIT_AFTER_ANSWER_SELECT: 700,
  WAIT_UNTIL_GAME_RESTART: 10000,
};
